/** localStorage segments under pos:{tenantId}:… for backup/export. */
export const TENANT_EXPORT_SEGMENTS = [
  'config',
  'users',
  'products',
  'categories',
  'orders',
  'customers',
  'registers',
  'draftCart',
  'draftCarts',
  'branches',
  'activeBranchId',
  'authSession',
  'dispensingLog',
  'kitchenQueue',
  'tableMap',
  'stockLogs',
  'heldCarts',
  'zReportClosed',
  'activeRegisterId',
  'appointments',
  'notifications',
]
